movies=[
{"title":"Interstellar","genre":["Sci-Fi","Adventure","Drama"],"keywords":["space","science","future","survival"],"rating":8.7},
{"title":"The Martian","genre":["Sci-Fi","Adventure","Drama"],"keywords":["space","survival","science","mars"],"rating":8.0},
{"title":"Inception","genre":["Sci-Fi","Action","Thriller"],"keywords":["dream","mind","technology","heist"],"rating":8.8},
{"title":"The Dark Knight","genre":["Action","Crime","Drama"],"keywords":["hero","crime","joker","batman"],"rating":9.0},
{"title":"The Dark Knight Rises","genre":["Action","Crime","Drama"],"keywords":["hero","crime","batman","revenge"],"rating":8.4},
{"title":"Avengers: Endgame","genre":["Action","Adventure","Sci-Fi"],"keywords":["superhero","marvel","time","battle"],"rating":8.4},
{"title":"Avengers: Infinity War","genre":["Action","Adventure","Sci-Fi"],"keywords":["superhero","marvel","space","battle"],"rating":8.4},
{"title":"Iron Man","genre":["Action","Adventure","Sci-Fi"],"keywords":["superhero","technology","marvel","robot"],"rating":7.9},
{"title":"Captain America: The Winter Soldier","genre":["Action","Adventure","Thriller"],"keywords":["superhero","spy","marvel","conspiracy"],"rating":7.7},
{"title":"Guardians of the Galaxy","genre":["Action","Adventure","Comedy","Sci-Fi"],"keywords":["space","superhero","marvel","team"],"rating":8.0},
{"title":"The Lord of the Rings: The Fellowship of the Ring","genre":["Fantasy","Adventure","Drama"],"keywords":["magic","journey","war","friendship"],"rating":8.9},
{"title":"The Lord of the Rings: The Two Towers","genre":["Fantasy","Adventure","Drama"],"keywords":["magic","war","friendship","kingdom"],"rating":8.8},
{"title":"The Lord of the Rings: The Return of the King","genre":["Fantasy","Adventure","Drama"],"keywords":["magic","war","kingdom","battle"],"rating":9.0},
{"title":"The Hobbit: An Unexpected Journey","genre":["Fantasy","Adventure"],"keywords":["magic","journey","dragon","adventure"],"rating":7.8},
{"title":"Harry Potter and the Philosopher's Stone","genre":["Fantasy","Adventure","Family"],"keywords":["magic","school","wizard","friendship"],"rating":7.6},
{"title":"Harry Potter and the Prisoner of Azkaban","genre":["Fantasy","Adventure","Mystery"],"keywords":["magic","wizard","school","mystery"],"rating":7.9},
{"title":"Harry Potter and the Goblet of Fire","genre":["Fantasy","Adventure","Drama"],"keywords":["magic","wizard","competition","school"],"rating":7.7},
{"title":"The Matrix","genre":["Sci-Fi","Action","Thriller"],"keywords":["technology","future","simulation","computer"],"rating":8.7},
{"title":"Blade Runner 2049","genre":["Sci-Fi","Drama","Mystery"],"keywords":["future","robots","technology","detective"],"rating":8.0},
{"title":"Arrival","genre":["Sci-Fi","Drama","Mystery"],"keywords":["aliens","language","science","space"],"rating":7.9},
{"title":"Gravity","genre":["Sci-Fi","Thriller","Drama"],"keywords":["space","survival","astronaut","accident"],"rating":7.7},
{"title":"Dune","genre":["Sci-Fi","Adventure","Drama"],"keywords":["desert","future","war","kingdom"],"rating":8.0},
{"title":"Dune: Part Two","genre":["Sci-Fi","Adventure","Drama"],"keywords":["desert","war","future","revenge"],"rating":8.5},
{"title":"Avatar","genre":["Sci-Fi","Adventure","Fantasy"],"keywords":["alien","planet","nature","war"],"rating":7.9},
{"title":"Avatar: The Way of Water","genre":["Sci-Fi","Adventure","Fantasy"],"keywords":["ocean","family","alien","nature"],"rating":7.5},
{"title":"Titanic","genre":["Romance","Drama"],"keywords":["love","ship","tragedy","relationship"],"rating":7.9},
{"title":"The Notebook","genre":["Romance","Drama"],"keywords":["love","relationship","family","emotions"],"rating":7.8},
{"title":"La La Land","genre":["Romance","Drama","Musical"],"keywords":["love","music","dreams","career"],"rating":8.0},
{"title":"The Fault in Our Stars","genre":["Romance","Drama"],"keywords":["love","illness","teenagers","emotions"],"rating":7.7},
{"title":"Crazy Rich Asians","genre":["Romance","Comedy"],"keywords":["love","family","wealth","relationship"],"rating":6.9},
{"title":"Toy Story","genre":["Animation","Comedy","Family"],"keywords":["friendship","toys","family","adventure"],"rating":8.3},
{"title":"Toy Story 3","genre":["Animation","Comedy","Family"],"keywords":["friendship","toys","family","adventure"],"rating":8.3},
{"title":"Finding Nemo","genre":["Animation","Adventure","Family"],"keywords":["ocean","family","friendship","journey"],"rating":8.2},
{"title":"The Incredibles","genre":["Animation","Action","Family"],"keywords":["superhero","family","adventure","team"],"rating":8.0},
{"title":"Coco","genre":["Animation","Fantasy","Family"],"keywords":["music","family","memory","tradition"],"rating":8.4},
{"title":"Inside Out","genre":["Animation","Comedy","Family"],"keywords":["emotions","mind","family","memory"],"rating":8.1},
{"title":"The Conjuring","genre":["Horror","Mystery","Thriller"],"keywords":["ghost","haunted","family","supernatural"],"rating":7.5},
{"title":"A Quiet Place","genre":["Horror","Sci-Fi","Thriller"],"keywords":["survival","monsters","family","silence"],"rating":7.5},
{"title":"Get Out","genre":["Horror","Mystery","Thriller"],"keywords":["mystery","family","psychology","escape"],"rating":7.7},
{"title":"It","genre":["Horror","Drama"],"keywords":["clown","friendship","childhood","fear"],"rating":7.3},
{"title":"The Hangover","genre":["Comedy"],"keywords":["friends","party","travel","fun"],"rating":7.7},
{"title":"Superbad","genre":["Comedy"],"keywords":["friends","school","party","teenagers"],"rating":7.6},
{"title":"Jumanji: Welcome to the Jungle","genre":["Comedy","Adventure","Fantasy"],"keywords":["game","friends","jungle","adventure"],"rating":6.9},
{"title":"Forrest Gump","genre":["Drama","Romance","Comedy"],"keywords":["life","friendship","love","journey"],"rating":8.8},
{"title":"The Shawshank Redemption","genre":["Drama"],"keywords":["prison","friendship","hope","freedom"],"rating":9.3},
{"title":"The Pursuit of Happyness","genre":["Drama"],"keywords":["family","career","struggle","success"],"rating":8.0},
{"title":"Whiplash","genre":["Drama","Music"],"keywords":["music","ambition","competition","success"],"rating":8.5},
{"title":"Jurassic Park","genre":["Sci-Fi","Adventure","Thriller"],"keywords":["dinosaurs","science","island","survival"],"rating":8.2},
{"title":"Pirates of the Caribbean","genre":["Adventure","Fantasy","Action"],"keywords":["pirates","ocean","treasure","adventure"],"rating":8.1},
{"title":"Indiana Jones and the Raiders of the Lost Ark","genre":["Adventure","Action"],"keywords":["treasure","archaeology","adventure","history"],"rating":8.4}
]